name: group_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_core: ^2.24.2
  image_picker: ^1.0.7
  firebase_auth: ^4.16.0
  file_picker: ^6.1.1
  path: ^1.9.0
  transparent_image: ^2.0.1
  image_cropper: ^5.0.1
  image_cropping: ^0.0.14
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  provider: ^6.1.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9

flutter:

  uses-material-design: true

